name: CI

on:
  push:
    branches:
    - main
    paths:
    - '**.swift'
    - '**.yml'
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  macOS:
    runs-on: macos-26
    timeout-minutes: 15
    steps:
    - name: Select appropriate Xcode version
      uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
      with:
        xcode-version: latest-stable
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - name: Build
      run: |
        swift build

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image: ["swift:6.1", "swift:6.2", "swift:6.3"]
    container:
      image: ${{ matrix.image }}
    env:
      ENABLE_HB_BENCHMARKS: true
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - name: Install libjemalloc-dev
      run: |
        apt-get -q update
        apt-get install -y libjemalloc-dev

    - name: Test
      run: |
        swift test --enable-code-coverage
    - name: Convert coverage files
      run: |
        llvm-cov export -format="lcov" \
          .build/debug/hummingbirdPackageTests.xctest \
          -ignore-filename-regex="\/Tests\/" \
          -ignore-filename-regex="\/Benchmarks\/" \
          -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 #v4.6.0
      with:
        files: info.lcov
        token: ${{ secrets.CODECOV_TOKEN }}
